name: Upload a build artifact to itch.io
description: 'Uploads a build artifact to itch.io with butler using the given api key and parameters.'
branding:
    icon: upload
    color: purple

inputs:
  - version-number:
    description: 'SemVer version number'
    required: true
    default: '0.0.0'
  - name:
    description: 'The build name'
    required: true
    default: 'unknown name'
  - build-path:
    description: "The artifact to upload"
    required: true
  - build-path:
    description: "The butler API Key to log in with"
    required: true
  
runs:  
  using: 'docker'
  image: 'Dockerfile'
  env:
    BUTLER_API_KEY: ${{ inputs.butler-api-key }}
    VERSION_NUMBER: ${{ inputs.version-number }}
    BUILD_NAME: ${{ inputs.name }}
    BUILD_PATH: ${{ inputs.build-path }}
